@startuml "GitOps example"

partition Development {
    "D1" --> "D2"
    "D2"----> "D3"
    "D3" --> "D4"
}

partition Feature1 {
    "F1.1" --> "F1.2"
}

partition Feature2 {
    "F2.1" --> "F2.2"
    "F2.2" --> "F2.3"
}

partition Release {
    "R1" -------> "R2"
}

partition Master {
    "0.1" ---------> "0.2"
}

"D1" --> F2.1
"D2" --> F1.1
"F1.2" --> "D3"
"F2.3" --> D4
"D4" --> "R2"
"R2" --> "0.2"
"0.1" --> "D1"

@enduml